name: sample-grpc-gateway-multi
services:
- name: apigw
  github:
    branch: multi
    repo: bojand/sample-grpc-gateway
  build_command: "make apigw"
  run_command: "./dist/apigw"
  envs:
  - key: SAMPLESVC_ADDR
    value: "samplesvc:5500"
    scope: RUN_TIME
  - key: PUBLIC_URL
    scope: RUN_TIME
    value: ${_self.PUBLIC_URL}
- name: samplesvc
  github:
    branch: multi
    repo: bojand/sample-grpc-gateway
  build_command: "make samplesvc"
  run_command: "./dist/samplesvc"
  internal_ports:
  - 5500